### ISSUE TITLE
expedition views should show loading indicator

### ISSUE THREAD

**Issue by rodney757** [biocodellc/geome-ui#11]
when viewing an expedition, there is an option to export data. when clicked, a loading indicator should appear

**Comment by mariadeck** [comment]
Fixed in merge #58

**Comment by rodney757** [comment]
http://develop.geome-db.org/workbench/expeditions/1162/settings still doesn't show a loading indicator

**Comment by rodney757** [comment]
okay, I see. It's there, but it centers in the top box and may not be visible if you're scrolled down the page
